Repository wanted-pre-onboarding-internship-1team/pre-onboarding-9th-3-1, pull requests merged in 2023-03, with the labels that each got.

#4 fix: Update README
  README.md
  package-lock.json
  package.json
Labels: Fix

#9 Feat/#1 seungyn
  .gitignore
  package-lock.json
  package.json
  public/data/mock.json
  src/App.tsx
  src/apis/index.ts
  src/apis/instance.ts
  src/apis/mockService.ts
  src/apis/temp.tsx
  src/apis/types/mock.ts
  src/components/Chart.tsx
  src/components/ChartHeader.tsx
  src/hooks/useMockList.ts
  src/index.tsx
  src/pages/Mainpage.tsx
  src/router/router.tsx
Labels: 구현완료, Merged, 리뷰요청

#18 Feat/#3 sujeong
  package-lock.json
  package.json
  src/common/temp.tsx
  src/components/Chart.tsx
  src/components/chart/Chart.tsx
  src/components/chart/ChartHeader.tsx
  src/components/filter/Filter.tsx
  src/components/filter/types/StyleProps.ts
  src/hooks/temp.tsx
  src/hooks/useQuerystring.ts
  src/pages/Mainpage.tsx
  tsconfig.json
Labels: 구현완료, 리뷰요청
